DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS doctor;
DROP TABLE IF EXISTS appointment;

CREATE TABLE patient (
  patientId INT generated by default as identity PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  address VARCHAR(250) NOT NULL,
  dob VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  mobile VARCHAR(250) NOT NULL
);

CREATE TABLE doctor (
doctorId INT generated by default as identity PRIMARY KEY,
name VARCHAR(250) NOT NULL,
email VARCHAR(250) NOT NULL
);

CREATE TABLE appointment (
  appointmentId INT generated by default as identity PRIMARY KEY,
  patientId INT,
  doctorId INT,
  date DATE NOT NULL,
  time VARCHAR(250) NOT NULL,
  foreign key (patientId) references patient(patientId),
  foreign key (doctorId) references doctor(doctorId)
);

INSERT INTO patient (patientId, name, address, dob, mobile, email) VALUES
(1, 'Ronan Keane', '1 Wilfield D04T712', '12/07/1998', '0871234567', 'rkeane@gmail.com'),
(2, 'Joe Bloggs', '1 Wilfield D04T712', '06/02/2000', '0878234567', 'jb@gmail.com'),
(3, 'Jane Doe', '1 Wilfield D04T712', '20/09/1990', '0871234537', 'jd@gmail.com');

INSERT INTO doctor (doctorId, name, email) VALUES
(1, 'Dr Micheal d Higgins', 'Dhigg@gmail.com'),
(2, 'Dr Sarah Quinn', 'sq@gmail.com'),
(3, 'Dr George Pin', 'gp@gmail.com'),
(4, 'Dr Wayne White', 'ww@gmail.com');

INSERT INTO appointment (appointmentId, patientId, doctorId, date, time) VALUES
(1,1,1,'2021-11-05','3:00'),
(4,2,1,'2021-11-05','4:00'),
(2,3,1,'2021-11-06','2:00'),
(3,2,2,'2021-11-05','3:00');
