DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS doctor;
DROP TABLE IF EXISTS booking;

CREATE TABLE patient (
  patientId INT generated by default as identity PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  address VARCHAR(250) NOT NULL,
  dob VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  mobile VARCHAR(250) NOT NULL
);

CREATE TABLE doctor (
doctorId INT generated by default as identity PRIMARY KEY,
name VARCHAR(250) NOT NULL,
email VARCHAR(250) NOT NULL
);

CREATE TABLE booking (
  bookingId INT generated by default as identity PRIMARY KEY,
  patientId INT,
  doctorId INT,
  bookingDate VARCHAR(250) NOT NULL,
  bookingTime VARCHAR(250) NOT NULL,
  foreign key (patientId) references patient(patientId),
  foreign key (doctorId) references doctor(doctorId)
);

INSERT INTO patient (patientId, name, address, dob, mobile, email) VALUES
(1, 'Ronan Keane', '1 Wilfield D04T712', '12/07/1998', '0871234567', 'rkeane@gmail.com'),
(2, 'Joe Bloggs', '1 Wilfield D04T712', '06/02/2000', '0878234567', 'jb@gmail.com'),
(3, 'Jane Doe', '1 Wilfield D04T712', '20/09/1990', '0871234537', 'jd@gmail.com');

INSERT INTO doctor (doctorId, name, email) VALUES
(1, 'Dr Micheal d Higgins', 'Dhigg@gmail.com'),
(2, 'Dr Sarah Quinn', 'sq@gmail.com'),
(3, 'Dr George Pin', 'gp@gmail.com'),
(4, 'Dr Wayne White', 'ww@gmail.com');

INSERT INTO booking (bookingId, patientId, doctorId, bookingDate, bookingTime) VALUES
(1,1,1,'05/11/2021','3:00'),
(4,2,1,'05/11/2021','4:00'),
(2,3,1,'06/11/2021','2:00'),
(3,2,2,'05/11/2021','3:00');
